//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Development/Small Projects/qLua/grammar/QLua.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace qLua.Compiler.CodeAnalysis {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="QLuaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IQLuaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChunk([NotNull] QLuaParser.ChunkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] QLuaParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat([NotNull] QLuaParser.StatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_semicolon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_semicolon([NotNull] QLuaParser.Stat_semicolonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_varassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_varassign([NotNull] QLuaParser.Stat_varassignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_break([NotNull] QLuaParser.Stat_breakContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_continue([NotNull] QLuaParser.Stat_continueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_goto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_goto([NotNull] QLuaParser.Stat_gotoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_do"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_do([NotNull] QLuaParser.Stat_doContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_while([NotNull] QLuaParser.Stat_whileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_repeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_repeat([NotNull] QLuaParser.Stat_repeatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_if([NotNull] QLuaParser.Stat_ifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_if_branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_if_branch([NotNull] QLuaParser.Stat_if_branchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_elseif_branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_elseif_branch([NotNull] QLuaParser.Stat_elseif_branchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_else_branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_else_branch([NotNull] QLuaParser.Stat_else_branchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_for([NotNull] QLuaParser.Stat_forContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.stat_forin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_forin([NotNull] QLuaParser.Stat_forinContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.classLevelStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassLevelStat([NotNull] QLuaParser.ClassLevelStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.clstat_func1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClstat_func1([NotNull] QLuaParser.Clstat_func1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.clstat_func2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClstat_func2([NotNull] QLuaParser.Clstat_func2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.clstat_vardecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClstat_vardecl([NotNull] QLuaParser.Clstat_vardeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.clstat_tabledecon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClstat_tabledecon([NotNull] QLuaParser.Clstat_tabledeconContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.clstat_classdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClstat_classdef([NotNull] QLuaParser.Clstat_classdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.clstat_interfacedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClstat_interfacedef([NotNull] QLuaParser.Clstat_interfacedefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.clstat_enumdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClstat_enumdef([NotNull] QLuaParser.Clstat_enumdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.attnamelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttnamelist([NotNull] QLuaParser.AttnamelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.attname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttname([NotNull] QLuaParser.AttnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.attrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrib([NotNull] QLuaParser.AttribContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.laststat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLaststat([NotNull] QLuaParser.LaststatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] QLuaParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncname([NotNull] QLuaParser.FuncnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarlist([NotNull] QLuaParser.VarlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamelist([NotNull] QLuaParser.NamelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplist([NotNull] QLuaParser.ExplistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp([NotNull] QLuaParser.ExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixexp([NotNull] QLuaParser.PrefixexpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctioncall([NotNull] QLuaParser.FunctioncallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarOrExp([NotNull] QLuaParser.VarOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] QLuaParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarSuffix([NotNull] QLuaParser.VarSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameAndArgs([NotNull] QLuaParser.NameAndArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] QLuaParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctiondef([NotNull] QLuaParser.FunctiondefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncbody([NotNull] QLuaParser.FuncbodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.funchead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunchead([NotNull] QLuaParser.FuncheadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParlist([NotNull] QLuaParser.ParlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] QLuaParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.paramVararg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamVararg([NotNull] QLuaParser.ParamVarargContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableconstructor([NotNull] QLuaParser.TableconstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldlist([NotNull] QLuaParser.FieldlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] QLuaParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldsep([NotNull] QLuaParser.FieldsepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorOr([NotNull] QLuaParser.OperatorOrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorAnd([NotNull] QLuaParser.OperatorAndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorComparison([NotNull] QLuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorStrcat([NotNull] QLuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorAddSub([NotNull] QLuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorMulDivMod([NotNull] QLuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorBitwise([NotNull] QLuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorUnary([NotNull] QLuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorPower([NotNull] QLuaParser.OperatorPowerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] QLuaParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] QLuaParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDefinition([NotNull] QLuaParser.EnumDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] QLuaParser.EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.enumProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumProperty([NotNull] QLuaParser.EnumPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValue([NotNull] QLuaParser.EnumValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.classDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDefinition([NotNull] QLuaParser.ClassDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.classExtends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassExtends([NotNull] QLuaParser.ClassExtendsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.classImplements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassImplements([NotNull] QLuaParser.ClassImplementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] QLuaParser.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDefinition([NotNull] QLuaParser.InterfaceDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceExtends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceExtends([NotNull] QLuaParser.InterfaceExtendsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceBody([NotNull] QLuaParser.InterfaceBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceStat([NotNull] QLuaParser.InterfaceStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceFunction([NotNull] QLuaParser.InterfaceFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceField([NotNull] QLuaParser.InterfaceFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.constructorCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorCall([NotNull] QLuaParser.ConstructorCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.constructorCallArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorCallArgs([NotNull] QLuaParser.ConstructorCallArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.typeAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeAnnotation([NotNull] QLuaParser.TypeAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.typeTuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeTuple([NotNull] QLuaParser.TypeTupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.nilableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilableType([NotNull] QLuaParser.NilableTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] QLuaParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.basicType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicType([NotNull] QLuaParser.BasicTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.funcType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncType([NotNull] QLuaParser.FuncTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableType([NotNull] QLuaParser.TableTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.tableField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableField([NotNull] QLuaParser.TableFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayType([NotNull] QLuaParser.ArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.baseTypeForArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseTypeForArray([NotNull] QLuaParser.BaseTypeForArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.tableDeconstructionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableDeconstructionList([NotNull] QLuaParser.TableDeconstructionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.tableDeconstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableDeconstruction([NotNull] QLuaParser.TableDeconstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.tableDeconstructionField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableDeconstructionField([NotNull] QLuaParser.TableDeconstructionFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] QLuaParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.moduleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclaration([NotNull] QLuaParser.ModuleDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.moduleDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclBody([NotNull] QLuaParser.ModuleDeclBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.moduleLevelDeclStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleLevelDeclStat([NotNull] QLuaParser.ModuleLevelDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclaration([NotNull] QLuaParser.ClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.classDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclBody([NotNull] QLuaParser.ClassDeclBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclaration([NotNull] QLuaParser.InterfaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclBody([NotNull] QLuaParser.InterfaceDeclBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.interfaceDeclStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclStat([NotNull] QLuaParser.InterfaceDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclaration([NotNull] QLuaParser.EnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QLuaParser.enumDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclBody([NotNull] QLuaParser.EnumDeclBodyContext context);
}
} // namespace qLua.Compiler.CodeAnalysis
